# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Category:
  fields:
    default: name, photo_id, base_colour, sort
    form: name, description, photo_id, base_colour, sort
  order_by: 
  relationships: photos
  filters: 
  search: name
  application: Photos

Photo:
  fields:
    default: title, sort, featured
    form: photo, title, description, flickr_url, featured, sort
  order_by: 
  relationships: categories
  filters: 
  search: title
  application: Photos

Page:
  fields:
    default: name, title
    form: name, title, content
  order_by:
  relationships:
  filters: 
  search: title
  application: Photos
